### ISSUE TITLE
Remove "Create an unprivileged user for day to day use."

### ISSUE THREAD

**Issue by quackerex** [beerisgood/macOS_Hardening#6]
It seems "using unprivileged user for day to day use" is outdated practice.

The current link is seems to be outdated site as it [links to an newer article](https://support.apple.com/en-au/HT201675) that does not have any information about this practice.

[This article](https://eclecticlight.co/2023/01/24/is-it-more-secure-to-be-a-normal-or-admin-user/) concludes:
>If you’re more comfortable with the more restricted privileges of a normal user account, then why not use one. But don’t think it’s going to improve security or privacy.

[Apple](https://support.apple.com/en-au/guide/mac-help/mh11402/mac) [recommends](https://support.apple.com/en-au/guide/mac-help/flvlt003/mac) unprivileged user account if more than one people use the Mac.

> If multiple people use your Mac, limit the number of users with administrator privileges.

> If multiple people use your Mac, you should set up a user account for each person, so that one person can’t modify the files needed by another. See [Set up users, guests and groups](https://support.apple.com/en-au/guide/mac-help/change-users-groups-settings-mtusr001/13.0/mac/13.0).

**Comment by beerisgood** [comment]
Apple still write on https://support.apple.com/guide/mac-help/mh11389/13.0/mac/13.0

(penultimate paragraph)
> Consider creating a standard user for your daily work and use the admin only when you need to install software or manage users.

let me think about it one more night.

**Comment by beerisgood** [comment]
Solved with https://github.com/beerisgood/macOS_Hardening/commit/8503ae23cfbb9e3f8fb3ea3e8d813290609e6b71

**Comment by beerisgood** [comment]
Solved with https://github.com/beerisgood/macOS_Hardening/commit/8503ae23cfbb9e3f8fb3ea3e8d813290609e6b71
